
spring:
  banner:
    location: banner.txt
  application:
    name: manage-staff-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/staffdb
    username: root
    password: Vishu@123
  jpa:
     hibernate.ddl-auto: update
     generate-ddl: true
     show-sql: true
logging:
  level:
    com:
      capgemini:
        managedepartmentservice: INFO
        
server:
  port: 8083